<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqm6skm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqm6skm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSqm6skm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSqm6skm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSqm6skm\appProdProjectContainer([
    'container.build_hash' => 'Sqm6skm',
    'container.build_id' => '28bfe282',
    'container.build_time' => 1644174071,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqm6skm');
